-- Script de Seed para Veículos de Exemplo (Carrera Imports)
-- Execute este script no SQL Editor do Supabase para popular o estoque inicial.

INSERT INTO vehicles (
  brand, 
  model, 
  version, 
  year, 
  mileage, 
  price, 
  category, 
  transmission, 
  fuel, 
  color, 
  city, 
  description, 
  blindagem, 
  status, 
  featured, 
  images
) VALUES 
(
  'Porsche', 
  '911 Carrera S', 
  '3.0 Flat-Six Turbo', 
  2023, 
  1200, 
  1150000, 
  'Esportivo', 
  'PDK 8 Speed', 
  'Gasolina', 
  'Cinza Arctic', 
  'São Paulo', 
  'Configuração exclusiva, interior em couro bordeaux, teto solar em vidro, escapamento esportivo.', 
  '', 
  'available', 
  true, 
  ARRAY['https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=1200&auto=format&fit=crop']
),
(
  'BMW', 
  'M4 Competition', 
  'xDrive Track Pack', 
  2024, 
  500, 
  890000, 
  'Esportivo', 
  'M Steptronic', 
  'Gasolina', 
  'Verde Isle of Man', 
  'São Paulo', 
  'Pacote de carbono completo, bancos concha M Carbon, freios de cerâmica.', 
  '', 
  'available', 
  true, 
  ARRAY['https://images.unsplash.com/photo-1603386329225-868f9b1ee6c9?q=80&w=1200&auto=format&fit=crop']
),
(
  'Audi', 
  'RS6 Avant', 
  'Performance 630cv', 
  2022, 
  15000, 
  980000, 
  'Station Wagon', 
  'Tiptronic 8 Speed', 
  'Gasolina', 
  'Nardo Gray', 
  'São Paulo', 
  'A perua mais rápida do mundo. Único dono, todas as revisões na concessionária.', 
  'Blindagem BSS Nível III-A', 
  'available', 
  true, 
  ARRAY['https://images.unsplash.com/photo-1614200187074-4e488257008b?q=80&w=1200&auto=format&fit=crop']
),
(
  'Land Rover', 
  'Range Rover Autobiography', 
  'D350 MHEV', 
  2023, 
  8000, 
  1350000, 
  'SUV', 
  'Automático 9 Speed', 
  'Diesel / Híbrido', 
  'Preto Santorini', 
  'São Paulo', 
  'O ápice do luxo off-road. Interior em couro semi-anilina, sistema de som Meridian Signature.', 
  'Blindagem Carbon Nível III-A', 
  'available', 
  true, 
  ARRAY['https://images.unsplash.com/photo-1541443131876-44b03de101c5?q=80&w=1200&auto=format&fit=crop']
),
(
  'Mercedes-Benz', 
  'GLC 43 AMG', 
  '4MATIC Coupé', 
  2021, 
  32000, 
  485000, 
  'SUV Coupé', 
  'AMG Speedshift 9G', 
  'Gasolina', 
  'Branco Polar', 
  'São Paulo', 
  'Esportividade e versatilidade. Teto solar panorâmico, escape performance AMG.', 
  '', 
  'available', 
  false, 
  ARRAY['https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?q=80&w=1200&auto=format&fit=crop']
);
